//! Account-group references bind to explicit and provider-default identities.

use super::validate_route_document;
use crate::routing::config::{
    ModelRoute, ProviderConfigYaml, ProviderCredentialYaml, RouteConfigYaml,
};
use serde_json::Value;
use std::collections::HashMap;

#[test]
fn account_groups_accept_explicit_and_provider_default_account_members() {
    let document = RouteConfigYaml {
        providers: vec![
            ProviderConfigYaml {
                test_plans: Vec::new(),
                test_policy: None,
                subpool_test_policies: Default::default(),
                default_account_test_policy: None,
                id: "managed-provider".to_string(),
                label: Some("Managed OpenAI".to_string()),
                vendor_key: None,
                vendor_name: None,
                preset: Some("openai".to_string()),
                base_url: "https://api.example.com/v1".to_string(),
                api_key: String::new(),
                auth_token: None,
                credential_storage_password: None,
                credential_storage_path: None,
                credential_archive_path: None,
                credential_storage_connection: None,
                credential_archive_connection: None,
                headers: HashMap::new(),
                extra_body: HashMap::new(),
                session_auth: None,
                keepalive: None,
                expires_at: None,
                runtime_state_object_key: None,
                account_name: None,
                execution_mode: None,
                endpoint_execution_modes: None,
                default_model: None,
                adapter: None,
                protocol_family: None,
                protocol_profile: None,
                supported_models: vec![],
                responses_path: None,
                chat_completions_path: None,
                completions_path: None,
                embeddings_path: None,
                audio_transcriptions_path: None,
                audio_speech_path: None,
                messages_path: None,
                search_path: None,
                fetch_path: None,
                research_path: None,
                balance_path: None,
                search_query_field: None,
                fetch_urls_field: None,
                model_map: HashMap::new(),
                model_map_targets: Default::default(),
                pool_target_size: None,
                pool_min_size: None,
                pool_refill_in_progress: false,
                auto_refill_enabled: false,
                auto_prune_enabled: false,
                scheduled_probe_enabled: false,
                scheduled_probe_interval_minutes: None,
                credential_permanent_delete_enabled: false,
                credential_automation_driver_id: None,
                credential_identity_categories: vec![],
                credentials: vec![ProviderCredentialYaml {
                    discovery: None,
                    test_policy: None,
                    id: Some("acc-prod-1".to_string()),
                    base_url: None,
                    api_key: Some("sk-prod-a".to_string()),
                    auth_token: None,
                    headers: HashMap::new(),
                    extra_body: HashMap::new(),
                    session_auth: None,
                    keepalive: None,
                    expires_at: None,
                    runtime_state_object_key: None,
                    account_name: Some("生产账号 A".to_string()),
                    credential_identity_category_id: None,
                    enabled: None,
                    scheduled_probe_enabled: false,
                    scheduled_probe_interval_minutes: None,
                    execution_mode: None,
                    endpoint_execution_modes: None,
                    supported_models: vec!["gpt-5.4".to_string()],
                    refresh_token: None,
                    refresh_endpoint: None,
                    refresh_client_id: None,
                    token_expires_in_secs: None,
                }],
            },
            ProviderConfigYaml {
                test_plans: Vec::new(),
                test_policy: None,
                subpool_test_policies: Default::default(),
                default_account_test_policy: None,
                id: "fallback-provider".to_string(),
                label: Some("Fallback".to_string()),
                vendor_key: None,
                vendor_name: None,
                preset: None,
                base_url: "https://fallback.example.com/v1".to_string(),
                api_key: "provider-level-key".to_string(),
                auth_token: None,
                credential_storage_password: None,
                credential_storage_path: None,
                credential_archive_path: None,
                credential_storage_connection: None,
                credential_archive_connection: None,
                headers: HashMap::new(),
                extra_body: HashMap::new(),
                session_auth: None,
                keepalive: None,
                expires_at: None,
                runtime_state_object_key: None,
                account_name: None,
                execution_mode: None,
                endpoint_execution_modes: None,
                default_model: None,
                adapter: None,
                protocol_family: None,
                protocol_profile: None,
                supported_models: vec![],
                responses_path: None,
                chat_completions_path: None,
                completions_path: None,
                embeddings_path: None,
                audio_transcriptions_path: None,
                audio_speech_path: None,
                messages_path: None,
                search_path: None,
                fetch_path: None,
                research_path: None,
                balance_path: None,
                search_query_field: None,
                fetch_urls_field: None,
                model_map: HashMap::new(),
                model_map_targets: Default::default(),
                pool_target_size: None,
                pool_min_size: None,
                pool_refill_in_progress: false,
                auto_refill_enabled: false,
                auto_prune_enabled: false,
                scheduled_probe_enabled: false,
                scheduled_probe_interval_minutes: None,
                credential_permanent_delete_enabled: false,
                credential_automation_driver_id: None,
                credential_identity_categories: vec![],
                credentials: vec![],
            },
        ],
        model_routes: vec![ModelRoute {
            pattern: "gpt-5.4".to_string(),
            provider_ids: vec!["managed-provider".to_string()],
            priority: 100,
            enabled: true,
        }],
        aliases: HashMap::new(),
        account_groups: vec![crate::routing::config::AccountGroupYaml {
            id: "group-vip".to_string(),
            name: "VIP".to_string(),
            description: None,
            billing_multiplier: Some(1.5),
            enabled: Some(true),
            notes: None,
            provider_credential_ids: vec![
                "acc-prod-1".to_string(),
                "fallback-provider::default".to_string(),
            ],
        }],
    };

    let validated = validate_route_document(document).expect("document should validate");
    let account_groups_value =
        serde_json::to_value(validated.document()).expect("validated document JSON");
    let groups = account_groups_value
        .get("account_groups")
        .and_then(Value::as_array)
        .expect("account_groups should serialize");
    assert_eq!(groups.len(), 1);
}

#[test]
fn account_groups_reject_unknown_account_members() {
    let document = RouteConfigYaml {
        providers: vec![ProviderConfigYaml {
            test_plans: Vec::new(),
            test_policy: None,
            subpool_test_policies: Default::default(),
            default_account_test_policy: None,
            id: "managed-provider".to_string(),
            label: Some("Managed OpenAI".to_string()),
            vendor_key: None,
            vendor_name: None,
            preset: Some("openai".to_string()),
            base_url: "https://api.example.com/v1".to_string(),
            api_key: String::new(),
            auth_token: None,
            credential_storage_password: None,
            credential_storage_path: None,
            credential_archive_path: None,
            credential_storage_connection: None,
            credential_archive_connection: None,
            headers: HashMap::new(),
            extra_body: HashMap::new(),
            session_auth: None,
            keepalive: None,
            expires_at: None,
            runtime_state_object_key: None,
            account_name: None,
            execution_mode: None,
            endpoint_execution_modes: None,
            default_model: None,
            adapter: None,
            protocol_family: None,
            protocol_profile: None,
            supported_models: vec![],
            responses_path: None,
            chat_completions_path: None,
            completions_path: None,
            embeddings_path: None,
            audio_transcriptions_path: None,
            audio_speech_path: None,
            messages_path: None,
            search_path: None,
            fetch_path: None,
            research_path: None,
            balance_path: None,
            search_query_field: None,
            fetch_urls_field: None,
            model_map: HashMap::new(),
            model_map_targets: Default::default(),
            pool_target_size: None,
            pool_min_size: None,
            pool_refill_in_progress: false,
            auto_refill_enabled: false,
            auto_prune_enabled: false,
            scheduled_probe_enabled: false,
            scheduled_probe_interval_minutes: None,
            credential_permanent_delete_enabled: false,
            credential_automation_driver_id: None,
            credential_identity_categories: vec![],
            credentials: vec![ProviderCredentialYaml {
                discovery: None,
                test_policy: None,
                id: Some("acc-prod-1".to_string()),
                base_url: None,
                api_key: Some("sk-prod-a".to_string()),
                auth_token: None,
                headers: HashMap::new(),
                extra_body: HashMap::new(),
                session_auth: None,
                keepalive: None,
                expires_at: None,
                runtime_state_object_key: None,
                account_name: Some("生产账号 A".to_string()),
                credential_identity_category_id: None,
                enabled: None,
                scheduled_probe_enabled: false,
                scheduled_probe_interval_minutes: None,
                execution_mode: None,
                endpoint_execution_modes: None,
                supported_models: vec!["gpt-5.4".to_string()],
                refresh_token: None,
                refresh_endpoint: None,
                refresh_client_id: None,
                token_expires_in_secs: None,
            }],
        }],
        model_routes: vec![],
        aliases: HashMap::new(),
        account_groups: vec![crate::routing::config::AccountGroupYaml {
            id: "group-vip".to_string(),
            name: "VIP".to_string(),
            description: None,
            billing_multiplier: Some(1.2),
            enabled: Some(true),
            notes: None,
            provider_credential_ids: vec!["missing-account".to_string()],
        }],
    };

    let diagnostics = validate_route_document(document).expect_err("group should fail");
    assert!(
        diagnostics
            .diagnostics
            .iter()
            .any(|entry| entry.code == "account_group_member_unknown"),
        "expected account_group_member_unknown diagnostics, got {diagnostics:?}"
    );
}
