#[cfg(feature = "line-accio-web-reverse-api")]
#[path = "accio/mod.rs"]
pub mod accio;
#[cfg(not(feature = "line-accio-web-reverse-api"))]
#[path = "accio_disabled.rs"]
pub mod accio;
pub mod aistudio_web;
pub mod anthropic;
pub mod anthropic_messages;
pub mod azure_openai;
pub mod bedrock_converse;
pub mod canonical;
#[cfg(feature = "line-chataibot-web-reverse")]
#[path = "chataibot/mod.rs"]
pub mod chataibot;
#[cfg(not(feature = "line-chataibot-web-reverse"))]
#[path = "chataibot_disabled.rs"]
pub mod chataibot;
pub mod chatgpt;
pub mod cohere;
pub mod freebuff;
pub mod gemini;
pub mod gemini_api;
pub mod gemini_business;
pub mod gemini_canvas;
pub mod gemini_web;
#[cfg(feature = "line-grok-web-reverse-api")]
#[path = "grok/mod.rs"]
pub mod grok;
#[cfg(not(feature = "line-grok-web-reverse-api"))]
#[path = "grok_disabled.rs"]
pub mod grok;
pub mod hooks;
#[cfg(feature = "line-kiro-official-vendor-api")]
pub mod kiro;
#[cfg(not(feature = "line-kiro-official-vendor-api"))]
#[path = "kiro_disabled.rs"]
pub mod kiro;
#[cfg(feature = "line-lumalabs-web-reverse-api")]
pub mod lumalabs;
#[cfg(not(feature = "line-lumalabs-web-reverse-api"))]
#[path = "lumalabs_disabled.rs"]
pub mod lumalabs;
pub mod openai;
pub mod producer;
pub mod qwen;
pub mod qwen_web;
pub mod registry;
pub mod responses;
#[cfg(feature = "family-search-api-compatible-official-api")]
pub mod search_api;
#[cfg(not(feature = "family-search-api-compatible-official-api"))]
#[path = "search_api_disabled.rs"]
pub mod search_api;
pub mod sse_parse;
pub(crate) mod stream_decode;
#[cfg(feature = "line-suno-web-reverse-api")]
pub mod suno;
#[cfg(not(feature = "line-suno-web-reverse-api"))]
#[path = "suno_disabled.rs"]
pub mod suno;
pub mod tool_choice;
pub mod tool_inject;
#[cfg(feature = "line-udio-web-reverse-api")]
pub mod udio;
#[cfg(not(feature = "line-udio-web-reverse-api"))]
#[path = "udio_disabled.rs"]
pub mod udio;
pub(crate) mod upstream_body;
pub mod xfyun_websocket;

// Legacy compatibility alias for older imports. New code should use
// `crate::protocol::search_api`.
pub use search_api as linkup;
