//! Analysis export, anomaly and remediation report registration.

use crate::http::routes::internal_requests;
use crate::state::AppState;
use axum::{
    routing::{get, post},
    Router,
};
use std::sync::Arc;

pub(super) fn mount(router: Router<Arc<AppState>>) -> Router<Arc<AppState>> {
    router
        .route(
            "/v1/internal/gateway/analysis/export",
            get(internal_requests::export_analysis_rows)
                .post(internal_requests::persist_analysis_export),
        )
        .route(
            "/v1/internal/gateway/analysis/exports",
            get(internal_requests::list_persisted_analysis_exports),
        )
        .route(
            "/v1/internal/gateway/analysis/exports/summary",
            get(internal_requests::summarize_persisted_analysis_exports),
        )
        .route(
            "/v1/internal/gateway/analysis/exports/baseline-report",
            get(internal_requests::get_analysis_export_baseline_report),
        )
        .route(
            "/v1/internal/gateway/analysis/exports/timeline-report",
            get(internal_requests::get_analysis_export_timeline_report),
        )
        .route(
            "/v1/internal/gateway/analysis/exports/trend-report",
            get(internal_requests::get_analysis_export_trend_report),
        )
        .route(
            "/v1/internal/gateway/analysis/exports/anomaly-report",
            get(internal_requests::get_analysis_export_anomaly_report),
        )
        .route(
            "/v1/internal/gateway/analysis/exports/diff",
            get(internal_requests::get_persisted_analysis_export_diff),
        )
        .route(
            "/v1/internal/gateway/analysis/exports/:exportId",
            get(internal_requests::get_persisted_analysis_export)
                .post(internal_requests::update_persisted_analysis_export_metadata),
        )
        .route(
            "/v1/internal/gateway/analysis/exports/cleanup-expired",
            post(internal_requests::cleanup_expired_analysis_exports),
        )
        .route(
            "/v1/internal/gateway/analysis/provider-routing/summary",
            get(internal_requests::summarize_provider_routing_analysis),
        )
        .route(
            "/v1/internal/gateway/analysis/rate-limit-hotspots",
            get(internal_requests::summarize_rate_limit_hotspots),
        )
        .route(
            "/v1/internal/gateway/analysis/rate-limit-hotspots/snapshot",
            post(internal_requests::persist_rate_limit_hotspot_snapshot),
        )
        .route(
            "/v1/internal/gateway/analysis/rate-limit-hotspots/snapshots",
            get(internal_requests::list_rate_limit_hotspot_snapshots),
        )
        .route(
            "/v1/internal/gateway/analysis/rate-limit-hotspots/snapshots/summary",
            get(internal_requests::summarize_rate_limit_hotspot_snapshot_inventory),
        )
        .route(
            "/v1/internal/gateway/analysis/rate-limit-hotspots/snapshots/trend-report",
            get(internal_requests::get_rate_limit_hotspot_snapshot_trend_report),
        )
        .route(
            "/v1/internal/gateway/analysis/rate-limit-hotspots/snapshots/:snapshotId",
            get(internal_requests::get_rate_limit_hotspot_snapshot),
        )
        .route(
            "/v1/internal/gateway/analysis/rate-limit-hotspots/trend-report",
            get(internal_requests::get_rate_limit_hotspot_trend_report),
        )
        .route(
            "/v1/internal/gateway/analysis/rate-limit-hotspots/anomaly-report",
            get(internal_requests::get_rate_limit_hotspot_anomaly_report),
        )
        .route(
            "/v1/internal/gateway/analysis/rate-limit-hotspots/anomaly-snapshot",
            post(internal_requests::persist_rate_limit_hotspot_anomaly_snapshot),
        )
        .route(
            "/v1/internal/gateway/analysis/rate-limit-hotspots/anomaly-snapshots",
            get(internal_requests::list_rate_limit_hotspot_anomaly_snapshots),
        )
        .route(
            "/v1/internal/gateway/analysis/rate-limit-hotspots/anomaly-snapshots/:snapshotId",
            get(internal_requests::get_rate_limit_hotspot_anomaly_snapshot),
        )
        .route(
            "/v1/internal/gateway/analysis/rate-limit-hotspots/anomaly-incidents/sync",
            post(internal_requests::sync_rate_limit_hotspot_anomaly_incidents),
        )
        .route(
            "/v1/internal/gateway/analysis/provider-routing/anomaly-report",
            get(internal_requests::get_provider_routing_anomaly_report),
        )
        .route(
            "/v1/internal/gateway/analysis/provider-routing/anomaly-incidents/sync",
            post(internal_requests::sync_provider_routing_anomaly_incidents),
        )
        .route(
            "/v1/internal/gateway/analysis/anomaly-policies",
            get(internal_requests::list_anomaly_policies)
                .post(internal_requests::save_anomaly_policy),
        )
        .route(
            "/v1/internal/gateway/analysis/anomaly-policies/:policy_id/sync",
            post(internal_requests::sync_anomaly_policy),
        )
        .route(
            "/v1/internal/gateway/analysis/anomaly-policies/sweep-sync",
            post(internal_requests::sweep_anomaly_policies),
        )
        .route(
            "/v1/internal/gateway/analysis/anomaly-policies/summary",
            get(internal_requests::summarize_anomaly_policies),
        )
        .route(
            "/v1/internal/gateway/analysis/anomaly-incidents",
            get(internal_requests::list_anomaly_incidents),
        )
        .route(
            "/v1/internal/gateway/analysis/anomaly-incidents/sync",
            post(internal_requests::sync_anomaly_incidents),
        )
        .route(
            "/v1/internal/gateway/analysis/anomaly-incidents/alert-queue",
            get(internal_requests::list_anomaly_incident_alert_queue),
        )
        .route(
            "/v1/internal/gateway/analysis/anomaly-incidents/:incidentId/history",
            get(internal_requests::list_anomaly_incident_history),
        )
        .route(
            "/v1/internal/gateway/analysis/anomaly-incidents/:incidentId/alert-dispatch",
            post(internal_requests::record_anomaly_incident_alert_dispatch),
        )
        .route(
            "/v1/internal/gateway/analysis/anomaly-incidents/:incidentId/remediation-plan",
            get(internal_requests::get_anomaly_incident_remediation_plan),
        )
        .route(
            "/v1/internal/gateway/analysis/anomaly-incidents/:incidentId/remediation-runs",
            get(internal_requests::list_incident_remediation_runs)
                .post(internal_requests::execute_incident_remediation_run),
        )
        .route(
            "/v1/internal/gateway/analysis/anomaly-incidents/summary",
            get(internal_requests::summarize_anomaly_incidents),
        )
        .route(
            "/v1/internal/gateway/analysis/remediation-runs",
            get(internal_requests::list_remediation_runs),
        )
        .route(
            "/v1/internal/gateway/analysis/remediation-queue",
            get(internal_requests::list_remediation_queue),
        )
        .route(
            "/v1/internal/gateway/analysis/remediation-runs/sweep",
            post(internal_requests::sweep_remediation_runs),
        )
        .route(
            "/v1/internal/gateway/analysis/remediation-runs/summary",
            get(internal_requests::summarize_remediation_runs),
        )
        .route(
            "/v1/internal/gateway/analysis/remediation-runs/effectiveness",
            get(internal_requests::summarize_remediation_effectiveness),
        )
        .route(
            "/v1/internal/gateway/analysis/remediation-runs/effectiveness/snapshot",
            post(internal_requests::persist_remediation_effectiveness_snapshot),
        )
        .route(
            "/v1/internal/gateway/analysis/remediation-runs/effectiveness/snapshots",
            get(internal_requests::list_remediation_effectiveness_snapshots),
        )
        .route(
            "/v1/internal/gateway/analysis/remediation-runs/effectiveness/snapshots/summary",
            get(internal_requests::summarize_remediation_effectiveness_snapshots),
        )
        .route(
            "/v1/internal/gateway/analysis/remediation-runs/effectiveness/snapshots/trend-report",
            get(internal_requests::get_remediation_effectiveness_trend_report),
        )
        .route(
            "/v1/internal/gateway/analysis/remediation-runs/effectiveness/snapshots/anomaly-report",
            get(internal_requests::get_remediation_effectiveness_snapshot_anomaly_report),
        )
        .route(
            "/v1/internal/gateway/analysis/remediation-runs/effectiveness/snapshots/anomaly-snapshots",
            get(internal_requests::list_remediation_effectiveness_anomaly_snapshots)
                .post(internal_requests::persist_remediation_effectiveness_anomaly_snapshot),
        )
        .route(
            "/v1/internal/gateway/analysis/remediation-runs/effectiveness/snapshots/anomaly-snapshots/:snapshotId",
            get(internal_requests::get_remediation_effectiveness_anomaly_snapshot),
        )
        .route(
            "/v1/internal/gateway/analysis/remediation-runs/effectiveness/snapshots/:snapshotId",
            get(internal_requests::get_remediation_effectiveness_snapshot),
        )
        .route(
            "/v1/internal/gateway/analysis/remediation-runs/:runId/impact",
            get(internal_requests::get_remediation_run_impact),
        )
        .route(
            "/v1/internal/gateway/analysis/remediation-runs/:runId/capture-impact",
            post(internal_requests::capture_remediation_run_impact),
        )
        .route(
            "/v1/internal/gateway/analysis/anomaly-incidents/:incidentId/acknowledge",
            post(internal_requests::acknowledge_anomaly_incident),
        )
        .route(
            "/v1/internal/gateway/analysis/anomaly-incidents/:incidentId/resolve",
            post(internal_requests::resolve_anomaly_incident),
        )
        .route(
            "/v1/internal/gateway/analysis/anomaly-incidents/:incidentId/follow-up",
            post(internal_requests::update_anomaly_incident_follow_up),
        )
}
