//! Credential checkout, project access and management access registration.

use crate::http::routes::{
    browser_executor, credentials, internal_access, internal_gateway, internal_provider_accounts,
    internal_provider_credentials, keepalive,
};
use crate::state::AppState;
use axum::{
    routing::{get, post},
    Router,
};
use std::sync::Arc;

pub(super) fn mount(router: Router<Arc<AppState>>) -> Router<Arc<AppState>> {
    router
        // -- Credential checkout -----------------------------------------
        .route("/v1/credentials/checkout", post(credentials::checkout))
        .route(
            "/v1/credentials/ensure",
            post(keepalive::ensure_credential_runtime),
        )
        .route(
            "/v1/internal/credentials/ensure",
            post(keepalive::ensure_credential_runtime),
        )
        .route(
            "/v1/internal/browser-executor/health",
            get(browser_executor::get_browser_executor_health),
        )
        .route(
            "/v1/internal/browser-executor/execute",
            post(browser_executor::execute_browser_executor),
        )
        // -- Internal gateway management ---------------------------------
        .route(
            "/v1/internal/gateway/api-access/resolve",
            post(internal_gateway::resolve_api_access),
        )
        .route(
            "/v1/internal/gateway/api-access/rotate",
            post(internal_gateway::rotate_api_access),
        )
        .route(
            "/v1/internal/gateway/benefit-projects/ensure",
            post(internal_gateway::ensure_benefit_project),
        )
        .route(
            "/v1/internal/gateway/projects/:project_id/api-access",
            get(internal_gateway::get_project_api_access),
        )
        .route(
            "/v1/internal/gateway/projects/:project_id/api-access/rotate",
            post(internal_gateway::rotate_project_api_access),
        )
        .route(
            "/v1/internal/gateway/projects/:project_id/prompt-cache/summary",
            get(internal_gateway::summarize_project_prompt_cache),
        )
        .route(
            "/v1/internal/gateway/projects/:project_id/prompt-cache/trend-report",
            get(internal_gateway::get_project_prompt_cache_trend_report),
        )
        .route(
            "/v1/internal/gateway/user-credentials/issue",
            post(internal_gateway::issue_user_credential),
        )
        .route(
            "/v1/internal/gateway/user-credentials/verify",
            post(internal_gateway::verify_user_credential),
        )
        .route(
            "/v1/internal/gateway/user-credentials/revoke",
            post(internal_gateway::revoke_user_credential),
        )
        .route(
            "/v1/internal/user-credentials/issue",
            post(internal_gateway::issue_user_credential),
        )
        .route(
            "/v1/internal/user-credentials/verify",
            post(internal_gateway::verify_user_credential),
        )
        .route(
            "/v1/internal/user-credentials/revoke",
            post(internal_gateway::revoke_user_credential),
        )
        .route(
            "/v1/internal/gateway/provider-credentials",
            get(internal_provider_credentials::list_provider_credentials)
                .post(internal_provider_credentials::create_provider_credential),
        )
        .route(
            "/v1/internal/gateway/provider-credentials/folder-sync/status",
            get(internal_provider_credentials::get_provider_credential_folder_sync_status)
                .put(internal_provider_credentials::update_provider_credential_folder_sync_status),
        )
        .route(
            "/v1/internal/gateway/provider-credentials/folder-sync/import",
            post(internal_provider_credentials::import_provider_credentials_from_folder),
        )
        .route(
            "/v1/internal/gateway/provider-credentials/folder-sync/export",
            post(internal_provider_credentials::export_provider_credentials_to_folder),
        )
        .route(
            "/v1/internal/gateway/provider-credentials/:provider_credential_id/quota",
            get(internal_provider_credentials::get_provider_credential_quota)
                .post(internal_provider_credentials::refresh_provider_credential_quota),
        )
        .route(
            "/v1/internal/gateway/provider-credentials/:provider_credential_id",
            get(internal_provider_credentials::get_provider_credential)
                .put(internal_provider_credentials::update_provider_credential)
                .delete(internal_provider_credentials::delete_provider_credential),
        )
        .route(
            "/v1/internal/gateway/provider-accounts/:provider_account_id/credentials",
            get(internal_provider_credentials::list_provider_credentials_for_account)
                .post(internal_provider_credentials::create_provider_credential_for_account),
        )
        .route(
            "/v1/internal/gateway/provider-inventory",
            get(internal_provider_accounts::get_provider_inventory),
        )
        .route(
            "/v1/internal/gateway/access/catalog",
            get(internal_access::get_access_catalog),
        )
        .route(
            "/v1/internal/gateway/access/provider-capabilities",
            post(internal_access::create_provider_capability),
        )
        .route(
            "/v1/internal/gateway/access/provider-capabilities/:access_id",
            post(internal_access::update_provider_capability),
        )
        .route(
            "/v1/internal/gateway/access/platform-access",
            post(internal_access::create_platform_access),
        )
        .route(
            "/v1/internal/gateway/access/platform-access/:access_id",
            post(internal_access::update_platform_access),
        )
        .route(
            "/v1/internal/gateway/access/bundles",
            post(internal_access::create_access_bundle),
        )
        .route(
            "/v1/internal/gateway/access/bundles/:bundle_id",
            post(internal_access::update_access_bundle)
                .delete(internal_access::delete_access_bundle),
        )
        .route(
            "/v1/internal/gateway/access/bundles/:bundle_id/items/replace",
            post(internal_access::replace_bundle_items),
        )
        .route(
            "/v1/internal/gateway/access/bundles/:bundle_id/user-keys/ensure",
            post(internal_access::ensure_bundle_user_key),
        )
        .route(
            "/v1/internal/gateway/access/keys",
            post(internal_access::create_access_key),
        )
        .route(
            "/v1/internal/gateway/access/keys/:access_key_id",
            post(internal_access::update_access_key).delete(internal_access::delete_access_key),
        )
        .route(
            "/v1/internal/gateway/access/keys/:access_key_id/rotate",
            post(internal_access::rotate_access_key),
        )
        .route(
            "/v1/internal/gateway/access/keys/:access_key_id/secret",
            post(internal_access::copy_access_key),
        )
        .route(
            "/v1/internal/gateway/access/keys/:access_key_id/enabled",
            post(internal_access::set_access_key_enabled),
        )
        .route(
            "/v1/internal/gateway/access/keys/:access_key_id/revoke",
            post(internal_access::revoke_access_key),
        )
        .route(
            "/v1/internal/gateway/access/keys/:access_key_id/balance",
            get(internal_access::get_access_key_balance),
        )
        .route(
            "/v1/internal/gateway/access/keys/:access_key_id/cash-ledger",
            get(internal_access::get_cash_ledger),
        )
        .route(
            "/v1/internal/gateway/access/keys/:access_key_id/balances/adjust",
            post(internal_access::adjust_access_key_balance),
        )
        .route(
            "/v1/internal/gateway/access/keys/:access_key_id/aggregate-memberships/replace",
            post(internal_access::replace_aggregate_memberships),
        )
        .route(
            "/v1/internal/gateway/access/preview/candidates",
            get(internal_access::preview_candidates),
        )
        .route(
            "/v1/internal/gateway/access/preview/route-decision",
            get(internal_access::preview_route_decision),
        )
        .route(
            "/v1/internal/gateway/access/affinity",
            get(internal_access::inspect_affinity).post(internal_access::reset_affinity),
        )
}
