//! Executor, provider, routing and Console configuration registration.

use crate::http::routes::{
    internal_account_groups, internal_browser_executor, internal_console,
    internal_provider_accounts, internal_requests, internal_routing, internal_runtime,
};
use crate::state::AppState;
use axum::{
    routing::{get, post},
    Router,
};
use std::sync::Arc;

pub(super) fn mount(router: Router<Arc<AppState>>) -> Router<Arc<AppState>> {
    router
        .route(
            "/v1/internal/gateway/browser-executor/nodes/heartbeat",
            post(internal_browser_executor::heartbeat_browser_executor_node),
        )
        .route(
            "/v1/internal/gateway/browser-executor/nodes",
            get(internal_browser_executor::list_browser_executor_nodes),
        )
        .route(
            "/v1/internal/gateway/browser-executor/slots",
            get(internal_browser_executor::list_browser_capability_slots)
                .post(internal_browser_executor::upsert_browser_capability_slot),
        )
        .route(
            "/v1/internal/gateway/browser-executor/leases/acquire",
            post(internal_browser_executor::acquire_browser_capability_lease),
        )
        .route(
            "/v1/internal/gateway/browser-executor/leases/:lease_id/release",
            post(internal_browser_executor::release_browser_capability_lease),
        )
        .route(
            "/v1/internal/gateway/browser-executor/leases",
            get(internal_browser_executor::list_browser_capability_leases),
        )
        .route(
            "/v1/internal/gateway/browser-executor/health",
            get(internal_browser_executor::get_browser_executor_management_health),
        )
        .route(
            "/v1/internal/gateway/model-associations",
            get(internal_requests::get_model_association_matrix),
        )
        .route(
            "/v1/internal/gateway/costs",
            get(internal_requests::get_cost_overview),
        )
        .route(
            "/v1/internal/gateway/provider-accounts",
            get(internal_provider_accounts::list_provider_accounts)
                .post(internal_provider_accounts::create_provider_account),
        )
        .route(
            "/v1/internal/gateway/provider-accounts/:provider_account_id",
            get(internal_provider_accounts::get_provider_account)
                .post(internal_provider_accounts::update_provider_account)
                .delete(internal_provider_accounts::delete_provider_account),
        )
        .route(
            "/v1/internal/gateway/provider-accounts/:provider_account_id/source-profile",
            post(internal_provider_accounts::patch_provider_source_profile),
        )
        .route(
            "/v1/internal/gateway/provider-accounts/:provider_account_id/model-tiering",
            get(internal_provider_accounts::get_provider_model_tiering)
                .post(internal_provider_accounts::save_provider_model_tiering),
        )
        .route(
            "/v1/internal/gateway/provider-accounts/:provider_account_id/model-pricing",
            post(internal_provider_accounts::patch_provider_model_pricing),
        )
        .route(
            "/v1/internal/gateway/provider-accounts/source-profile/backfill",
            post(internal_provider_accounts::backfill_provider_source_profiles),
        )
        .route(
            "/v1/internal/gateway/provider-accounts/:provider_account_id/probe",
            post(internal_provider_accounts::probe_provider_account),
        )
        .route(
            "/v1/internal/gateway/provider-accounts/:provider_account_id/quota",
            get(internal_provider_accounts::get_provider_quota)
                .post(internal_provider_accounts::refresh_provider_quota),
        )
        .route(
            "/v1/internal/gateway/provider-quotas/:provider_account_id",
            get(internal_provider_accounts::get_provider_quota)
                .post(internal_provider_accounts::refresh_provider_quota),
        )
        .route(
            "/v1/internal/gateway/provider-accounts/sweep-cooling",
            post(internal_provider_accounts::sweep_cooling_provider_accounts),
        )
        .route(
            "/v1/internal/gateway/route-policies",
            get(internal_routing::list_route_policies).post(internal_routing::create_route_policy),
        )
        .route(
            "/v1/internal/gateway/route-policies/:policy_id",
            post(internal_routing::update_route_policy),
        )
        .route(
            "/v1/internal/gateway/model-aliases",
            get(internal_routing::list_model_aliases).post(internal_routing::create_model_alias),
        )
        .route(
            "/v1/internal/gateway/model-aliases/:alias_id",
            post(internal_routing::update_model_alias).delete(internal_routing::delete_model_alias),
        )
        .route(
            "/v1/internal/gateway/readiness",
            get(internal_runtime::get_gateway_readiness),
        )
        .route(
            "/v1/internal/gateway/operations/summary",
            get(internal_runtime::get_gateway_operator_summary),
        )
        .route(
            "/v1/internal/gateway/account-groups",
            get(internal_account_groups::get_account_groups_summary),
        )
        .route(
            "/v1/internal/gateway/runtime/drain",
            post(internal_runtime::drain_gateway_runtime),
        )
        .route(
            "/v1/internal/gateway/route-config",
            get(internal_console::get_route_config).post(internal_console::commit_route_config),
        )
        .route(
            "/v1/internal/gateway/console/route-config",
            get(internal_console::get_route_config).put(internal_console::commit_route_config),
        )
        .route(
            "/v1/internal/gateway/console/bootstrap/status",
            get(internal_console::get_bootstrap_status),
        )
        .route(
            "/v1/internal/gateway/console/bootstrap",
            post(internal_console::bootstrap_console_admin),
        )
        .route(
            "/v1/internal/gateway/console/session/verify",
            post(internal_console::verify_console_session),
        )
        .route(
            "/v1/internal/gateway/console/session/confirm-secret-access",
            post(internal_console::confirm_console_secret_access),
        )
        .route(
            "/v1/internal/gateway/console/session/rotate",
            post(internal_console::rotate_console_session),
        )
        .route(
            "/v1/internal/gateway/console/session/logout",
            post(internal_console::logout_console_session),
        )
        .route(
            "/v1/internal/gateway/console/credentials/:credential_id/probe",
            post(internal_console::probe_console_credential),
        )
        .route(
            "/v1/internal/gateway/console/providers/:provider_id/probe",
            post(internal_console::probe_console_provider),
        )
        .route(
            "/v1/internal/gateway/console/gemini-auth-sessions",
            post(internal_console::create_gemini_auth_session),
        )
        .route(
            "/v1/internal/gateway/console/gemini-auth-sessions/:session_id",
            get(internal_console::get_gemini_auth_session),
        )
        .route(
            "/v1/internal/gateway/console/gemini-auth-sessions/:session_id/complete",
            post(internal_console::complete_gemini_auth_session),
        )
        .route(
            "/v1/internal/gateway/console/route-config/validate",
            post(internal_console::validate_route_config),
        )
        .route(
            "/v1/internal/gateway/route-config/revisions",
            get(internal_console::list_route_config_revisions),
        )
        .route(
            "/v1/internal/gateway/route-config/revisions/:revision_id",
            get(internal_console::get_route_config_revision),
        )
        .route(
            "/v1/internal/gateway/console/revisions",
            get(internal_console::list_route_config_revisions),
        )
        .route(
            "/v1/internal/gateway/console/revisions/:revision_id",
            get(internal_console::get_route_config_revision),
        )
}
